import { Category, App } from '@/types';

export const CATEGORIES: Category[] = [
  { id: 1, name: 'AI Tools', slug: 'ai', icon: '🤖', color: 'bg-purple-500', description: 'AI-powered apps and tools' },
  { id: 2, name: 'Games', slug: 'games', icon: '🎮', color: 'bg-blue-500', description: 'Browser-based games' },
  { id: 3, name: 'Productivity', slug: 'productivity', icon: '⚡', color: 'bg-yellow-500', description: 'Tools to get things done' },
  { id: 4, name: 'Creative', slug: 'creative', icon: '🎨', color: 'bg-pink-500', description: 'Design and creative tools' },
  { id: 5, name: 'Finance', slug: 'finance', icon: '💰', color: 'bg-green-500', description: 'Finance and calculators' },
  { id: 6, name: 'Education', slug: 'education', icon: '📚', color: 'bg-orange-500', description: 'Learning and educational apps' },
  { id: 7, name: 'Fun', slug: 'fun', icon: '🎉', color: 'bg-red-500', description: 'Just for fun' },
  { id: 8, name: 'Utilities', slug: 'utilities', icon: '🔧', color: 'bg-gray-500', description: 'Handy utilities' },
];

export const SEED_APPS: Omit<App, 'id' | 'created_at' | 'category'>[] = [
  {
    name: 'Pomodoro Beast',
    tagline: 'The most satisfying pomodoro timer ever built',
    description: 'A beautiful pomodoro timer with ambient sounds, streak tracking, and satisfying animations that make focusing actually enjoyable.',
    url: 'https://pomodorobeast.com',
    screenshot_url: null,
    category_id: 3,
    author_name: 'Alex Chen',
    author_url: null,
    github_url: null,
    tags: ['productivity', 'timer', 'focus'],
    votes: 342,
    featured: true,
    approved: true,
  },
  {
    name: 'PixelDraw',
    tagline: 'Pixel art editor that runs in your browser',
    description: 'Create stunning pixel art with a full-featured editor. Supports layers, animation frames, and direct export to PNG/GIF.',
    url: 'https://pixeldraw.app',
    screenshot_url: null,
    category_id: 4,
    author_name: 'Maria Santos',
    author_url: null,
    github_url: 'https://github.com/example/pixeldraw',
    tags: ['pixel art', 'drawing', 'animation'],
    votes: 289,
    featured: true,
    approved: true,
  },
  {
    name: 'Budget Buddy',
    tagline: 'Track expenses without the spreadsheet hell',
    description: 'Simple personal finance tracker with beautiful charts. No signup needed — everything stays in your browser.',
    url: 'https://budgetbuddy.app',
    screenshot_url: null,
    category_id: 5,
    author_name: 'James Park',
    author_url: null,
    github_url: null,
    tags: ['finance', 'budgeting', 'charts'],
    votes: 198,
    featured: false,
    approved: true,
  },
  {
    name: 'TypingDojo',
    tagline: 'Get faster at typing with daily challenges',
    description: 'Daily typing challenges ranked by difficulty. Compete on global leaderboards and track your WPM progress over time.',
    url: 'https://typingdojo.io',
    screenshot_url: null,
    category_id: 6,
    author_name: 'Nina Kim',
    author_url: null,
    github_url: 'https://github.com/example/typingdojo',
    tags: ['typing', 'speed', 'education'],
    votes: 167,
    featured: false,
    approved: true,
  },
  {
    name: 'Maze Runner 2D',
    tagline: 'Procedurally generated maze game with a twist',
    description: 'Every maze is unique. Features 10+ environments, enemy AI, and a competitive speedrun mode.',
    url: 'https://mazerunner2d.com',
    screenshot_url: null,
    category_id: 2,
    author_name: 'Tom Walker',
    author_url: null,
    github_url: null,
    tags: ['maze', 'procedural', 'speedrun'],
    votes: 445,
    featured: true,
    approved: true,
  },
  {
    name: 'QuickResume',
    tagline: 'AI-powered resume builder in 5 minutes',
    description: 'Describe your experience in plain English and get a polished resume in seconds. ATS-optimized templates included.',
    url: 'https://quickresume.ai',
    screenshot_url: null,
    category_id: 1,
    author_name: 'Sarah Lee',
    author_url: null,
    github_url: null,
    tags: ['resume', 'AI', 'career'],
    votes: 512,
    featured: true,
    approved: true,
  },
  {
    name: 'ColorPalette Generator',
    tagline: 'Generate beautiful color palettes from any image',
    description: 'Upload any image and extract a stunning color palette. Export to CSS, Tailwind, Figma, or copy hex codes instantly.',
    url: 'https://colorpalette.io',
    screenshot_url: null,
    category_id: 4,
    author_name: 'Luca Rossi',
    author_url: null,
    github_url: 'https://github.com/example/colorpalette',
    tags: ['design', 'colors', 'CSS'],
    votes: 234,
    featured: false,
    approved: true,
  },
  {
    name: 'WordSprint',
    tagline: 'Multiplayer word game for competitive souls',
    description: 'Play word games in real-time with friends. 8 game modes, voice chat support, and weekly tournaments.',
    url: 'https://wordsprint.gg',
    screenshot_url: null,
    category_id: 2,
    author_name: 'Emma Wilson',
    author_url: null,
    github_url: null,
    tags: ['word game', 'multiplayer', 'competitive'],
    votes: 378,
    featured: false,
    approved: true,
  },
  {
    name: 'GIF Maker Pro',
    tagline: 'Turn any video clip into a perfect GIF',
    description: 'Upload a video, trim, add captions, adjust speed, and download a high-quality GIF. No watermarks. All in browser.',
    url: 'https://gifmakerpro.com',
    screenshot_url: null,
    category_id: 8,
    author_name: 'Dev Studio',
    author_url: null,
    github_url: null,
    tags: ['GIF', 'video', 'converter'],
    votes: 621,
    featured: true,
    approved: true,
  },
  {
    name: 'StudyFlash',
    tagline: 'Spaced repetition flashcards that actually work',
    description: 'Create and share flashcard decks. Uses proven spaced repetition algorithms to maximize retention.',
    url: 'https://studyflash.app',
    screenshot_url: null,
    category_id: 6,
    author_name: 'Min-ji Cho',
    author_url: null,
    github_url: 'https://github.com/example/studyflash',
    tags: ['flashcards', 'spaced repetition', 'study'],
    votes: 287,
    featured: false,
    approved: true,
  },
  {
    name: 'Noise Machine',
    tagline: 'Ambient sounds for deep work sessions',
    description: 'Mix rain, coffee shop, lo-fi music, and 50+ other sounds. Save your perfect mix and share with others.',
    url: 'https://noisemachine.app',
    screenshot_url: null,
    category_id: 3,
    author_name: 'Kai Müller',
    author_url: null,
    github_url: null,
    tags: ['ambient', 'focus', 'sounds'],
    votes: 419,
    featured: false,
    approved: true,
  },
  {
    name: 'Roast My Code',
    tagline: 'AI roasts your code (lovingly)',
    description: 'Paste your code and get brutally honest (but funny) AI feedback. Actually useful for learning good practices.',
    url: 'https://roastmycode.dev',
    screenshot_url: null,
    category_id: 1,
    author_name: 'Fun Dev',
    author_url: null,
    github_url: null,
    tags: ['AI', 'code review', 'humor'],
    votes: 893,
    featured: true,
    approved: true,
  },
];
